"""Project runtime configuration defaults."""

import os

DOMAINS = [
    "Agriculture",
    "Geoscience",
    "Computer Science",
    "Supply Chain",
    "Environment",
]

TOP_N_PAPERS = 15
MAX_GRAPH_NODES = 200
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
SPARSE_GRAPH_THRESHOLD = 3
DEFAULT_EXTRACTION_TOP_K = 8

# Session/cache behaviour
SESSION_QUERY_SIMILARITY_THRESHOLD = 0.82
FOLLOWUP_SKIP_RETRIEVAL_SIMILARITY = 0.93
SESSION_CACHE_TTL_SECONDS = 1800

# Fast-mode retrieval/filtering
FAST_MODE_TOP_N_PAPERS = 10
FAST_MODE_TOP_K_PAPERS = 5

# Entity extraction
ENTITY_EXTRACTION_MAX_WORKERS = 4
ENTITY_EXTRACTION_MODEL = os.getenv("ENTITY_EXTRACTION_MODEL", "llama-3.1-8b-instant")
ENTITY_EXTRACTION_FAST_MODEL = os.getenv("ENTITY_EXTRACTION_FAST_MODEL", "llama-3.1-8b-instant")
USE_FAST_EXTRACTOR_IN_FAST_MODE = os.getenv("USE_FAST_EXTRACTOR_IN_FAST_MODE", "1") == "1"
ENTITY_EXTRACTION_MAX_CONCURRENCY = int(os.getenv("ENTITY_EXTRACTION_MAX_CONCURRENCY", "5"))
USE_OLLAMA_EXTRACTION_FALLBACK = os.getenv("USE_OLLAMA_EXTRACTION_FALLBACK", "0") == "1"
OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_EXTRACTION_MODEL = os.getenv("OLLAMA_EXTRACTION_MODEL", "llama3.1:8b")
USE_OLLAMA_PRIMARY = os.getenv("USE_OLLAMA_PRIMARY", "0") == "1"
OLLAMA_GENERAL_MODEL = os.getenv("OLLAMA_GENERAL_MODEL", "llama3.1:8b")
OLLAMA_TIMEOUT_SECONDS = int(os.getenv("OLLAMA_TIMEOUT_SECONDS", "180"))

# Prompt/context budgets
MAX_CONTEXT_TRIPLES = 30
MAX_ABSTRACT_TOKENS = 180
ANSWER_PROMPT_TOKEN_BUDGET = 2400

# Confidence-driven control
GRAPH_CONFIDENCE_THRESHOLD = 0.55
MAX_GRAPH_EXPANSION_ITERS = 2
LOW_CONFIDENCE_EXTRA_TOP_N = 8

# Query understanding and planning
QUERY_PLANNER_MODEL = os.getenv("QUERY_PLANNER_MODEL", "llama-3.1-8b-instant")
QUERY_PLANNER_MAX_TOKENS = int(os.getenv("QUERY_PLANNER_MAX_TOKENS", "350"))
QUERY_PLANNER_TEMPERATURE = float(os.getenv("QUERY_PLANNER_TEMPERATURE", "0.1"))

# Plan-aware retrieval and adaptive controls
PLAN_AWARE_RETRIEVAL_ALPHA = float(os.getenv("PLAN_AWARE_RETRIEVAL_ALPHA", "0.6"))
PLAN_AWARE_RETRIEVAL_BETA = float(os.getenv("PLAN_AWARE_RETRIEVAL_BETA", "0.25"))
PLAN_AWARE_RETRIEVAL_GAMMA = float(os.getenv("PLAN_AWARE_RETRIEVAL_GAMMA", "0.15"))
GRAPH_MIN_CONNECTIVITY_BASE = float(os.getenv("GRAPH_MIN_CONNECTIVITY_BASE", "0.12"))
GRAPH_MIN_REQUIRED_TYPES_BASE = int(os.getenv("GRAPH_MIN_REQUIRED_TYPES_BASE", "2"))

# Confidence and coverage scoring
CONFIDENCE_MIN_SUPPORT_PAPERS = int(os.getenv("CONFIDENCE_MIN_SUPPORT_PAPERS", "3"))
CONFIDENCE_MIN_REASONING_PATHS = int(os.getenv("CONFIDENCE_MIN_REASONING_PATHS", "2"))
